[project]
name = "probetag-werki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.21.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
